import streamlit as st 

st.title("Hello, Streamlit!")
st.write("This is a simple Leaning app using Streamlit.")


st.button("Click me!")
st.checkbox("Check me!")
st.radio("Choose one:", ["Option 1", "Option 2", "Option 3"])
st.selectbox("Select one:", ["Choice A", "Choice B", "Choice C"])
st.multiselect("Select multiple:", ["Item 1", "Item 2", "Item 3"])
st.slider("Slide me:", 0, 100, 50)
st.text_input("Enter some text:")
st.text_area("Enter a longer text:")
st.date_input("Pick a date:")
st.time_input("Pick a time:")
st.file_uploader("Upload a file:")
st.color_picker("Pick a color:")
st.progress(50)
st.balloons()
st.sidebar.title("Sidebar")
st.sidebar.button("Sidebar Button")
st.sidebar.checkbox("Sidebar Checkbox")
st.sidebar.radio("Sidebar Radio:", ["S1", "S2", "S3"])
st.sidebar.selectbox("Sidebar Selectbox:", ["A", "B", "C"])
st.sidebar.multiselect("Sidebar Multiselect:", ["X", "Y", "Z"])
st.sidebar.slider("Sidebar Slider:", 0, 100, 25)
st.sidebar.text_input("Sidebar Text Input:")
st.sidebar.text_area("Sidebar Text Area:")
st.sidebar.date_input("Sidebar Date Input:")
st.sidebar.time_input("Sidebar Time Input:")
st.sidebar.file_uploader("Sidebar File Uploader:")
st.sidebar.color_picker("Sidebar Color Picker:")
st.sidebar.progress(75)
st.sidebar.balloons()

st.write("This is a simple Leaning app using Streamlit.")
